### PR TITLE
Add node test github workflow

### PR DESCRIPTION
**Pull request by mzgoddard**
Run `npm test` on github actions on windows.

### CODE REVIEW

**Comment by mzgoddard** [comment]
@jugglinmike I was trying to debug why the `rejects invalid "pressKey" Command` test was failing with a mismatch on `message: 'Invalid key code specified.'`. I realized the `main` branch is also failing.

**Comment by mzgoddard** [comment]
The current failure in the workflow is in `npm ci`. The `postinstall` script is failing since MakeVoice doesn't exist in the CI environment.

Hmm.

**Comment by jugglinmike** [comment]
> The current failure in the workflow is in `npm ci`. The `postinstall` script is failing since MakeVoice doesn't exist in the CI environment.
> 
> Hmm.

We can still execute the tests even if the `npm ci` step fails for that reason. How about applying [the `continue-on-error` feature](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) to that step for now? Doing so will make it slightly harder to identify failures that result from a problem with installing packages, but compared to the risks of continuing to develop this project without any CI at all, I think that's acceptable.

**Comment by mzgoddard** [comment]
@jugglinmike I rebased onto main and added `continue-on-error` to `npm ci` step. I guess the next step would be to run prettier in a different PR or this one. (Or merge this and do that as a follow up.)

**Pull request merged**
